export {default as Instagram} from './Instagram';
export {default as GitHub} from './GitHub';
export {default as LinkedIn} from './LinkedIn';
export {default as Twitter} from './Twitter';
export {default as YouTube} from './YouTube';
export {default as Bag} from './Bag';
export {default as Hamburger} from './Hamburger';
export {default as Love} from './Love';
export {default as Search} from './Search';
